[package]
name = "aether-crypto-bls"
version.workspace = true
edition.workspace = true

[dependencies]
blst.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true

