# Aether Blockchain - Clippy Linting Configuration

# Deny certain lints
# These are errors, not warnings
msrv = "1.75"

# Cognitive complexity threshold
cognitive-complexity-threshold = 30

# Allow certain lints that can be overly pedantic
avoid-breaking-exported-api = false

