[package]
name = "aether-rpc-json"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
warp = "0.3"
hex = "0.4"

aether-types = { path = "../../types" }
aether-ledger = { path = "../../ledger" }

