[package]
name = "aether-rpc-json"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
warp = "0.3"
hex = "0.4"
futures = "0.3"
bincode.workspace = true

aether-types = { path = "../../types" }
aether-ledger = { path = "../../ledger" }
aether-consensus = { path = "../../consensus" }
aether-mempool = { path = "../../mempool" }

[dev-dependencies]
tempfile = "3"
aether-state-storage = { path = "../../state/storage" }
aether-crypto-primitives = { path = "../../crypto/primitives" }
aether-crypto-vrf = { path = "../../crypto/vrf" }
