[package]
name = "aether-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
wasmtime.workspace = true
serde.workspace = true

aether-types = { path = "../types" }
aether-ledger = { path = "../ledger" }

