[package]
name = "aether-program-reputation"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
anyhow.workspace = true

aether-types = { path = "../../types" }

