[package]
name = "aether-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "aetherctl"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
toml = "0.8"
dirs = "5"
clap = { version = "4.5", features = ["derive"] }
hex = "0.4"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }

aether-types = { path = "../../types" }
aether-crypto-primitives = { path = "../../crypto/primitives" }
aether-sdk = { path = "../../sdk/rust" }
aether-consensus = { path = "../../consensus" }
aether-node = { path = "../../node" }
aether-state-storage = { path = "../../state/storage" }
aether-state-snapshots = { path = "../../state/snapshots" }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
