[package]
name = "aether-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "aetherctl"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true

aether-types = { path = "../../types" }
aether-crypto-primitives = { path = "../../crypto/primitives" }

