[package]
name = "aether-verifiers-tee"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true

# TEE attestation libraries (e.g., snp-verifier, tdx-verifier)

