[package]
name = "aether-verifiers-vcr"
version.workspace = true
edition.workspace = true

[dependencies]
aether-types = { path = "../../types" }
serde.workspace = true
anyhow.workspace = true
thiserror.workspace = true
