[package]
name = "aether-verifiers-vcr"
version.workspace = true
edition.workspace = true

[dependencies]
aether-types = { path = "../../types" }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true

aether-types = { path = "../../types" }
aether-verifiers-tee = { path = "../tee" }
aether-verifiers-kzg = { path = "../kzg-verifier" }
aether-crypto-primitives = { path = "../../crypto/primitives" }

