[package]
name = "aether-state-snapshots"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
tokio.workspace = true
bincode.workspace = true
zstd = "0.13"

aether-types = { path = "../../types" }
aether-state-storage = { path = "../storage" }
aether-state-merkle = { path = "../merkle" }

[dev-dependencies]
tempfile = "3"
