[package]
name = "aether-crypto-primitives"
version.workspace = true
edition.workspace = true

[dependencies]
ed25519-dalek = "2"
sha2.workspace = true
blake3.workspace = true
thiserror.workspace = true
rand = "0.8"

