[package]
name = "aether-types"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
bincode.workspace = true
sha2.workspace = true
hex = "0.4"
anyhow.workspace = true
aether-crypto-primitives = { path = "../crypto/primitives" }
