[package]
name = "aether-program-job-escrow"
version.workspace = true
edition.workspace = true

[dependencies]
aether-types = { path = "../../types" }
aether-verifiers-vcr = { path = "../../verifiers/vcr-validator" }
serde.workspace = true
anyhow.workspace = true
