[package]
name = "aether-crypto-vrf"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
sha2 = "0.10"
rand = "0.8"
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true

# VRF implementation (e.g., schnorrkel for ECVRF)

