[package]
name = "aether-da-turbine"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
anyhow.workspace = true

aether-da-erasure = { path = "../erasure-coding" }
aether-da-shreds = { path = "../shreds" }
aether-types = { path = "../../types" }

